/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: obd2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "obd2.pb-c.h"
void obd2__obd2_data__init(Obd2__OBD2Data *message) {
  static const Obd2__OBD2Data init_value = OBD2__OBD2_DATA__INIT;
  *message = init_value;
}
size_t obd2__obd2_data__get_packed_size(const Obd2__OBD2Data *message) {
  assert(message->base.descriptor == &obd2__obd2_data__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t obd2__obd2_data__pack(const Obd2__OBD2Data *message, uint8_t *out) {
  assert(message->base.descriptor == &obd2__obd2_data__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t obd2__obd2_data__pack_to_buffer(const Obd2__OBD2Data *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &obd2__obd2_data__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Obd2__OBD2Data *obd2__obd2_data__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Obd2__OBD2Data *)protobuf_c_message_unpack(&obd2__obd2_data__descriptor, allocator, len, data);
}
void obd2__obd2_data__free_unpacked(Obd2__OBD2Data *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &obd2__obd2_data__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void obd2__obd2_msg_struct__init(Obd2__OBD2MsgStruct *message) {
  static const Obd2__OBD2MsgStruct init_value = OBD2__OBD2_MSG_STRUCT__INIT;
  *message = init_value;
}
size_t obd2__obd2_msg_struct__get_packed_size(const Obd2__OBD2MsgStruct *message) {
  assert(message->base.descriptor == &obd2__obd2_msg_struct__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t obd2__obd2_msg_struct__pack(const Obd2__OBD2MsgStruct *message, uint8_t *out) {
  assert(message->base.descriptor == &obd2__obd2_msg_struct__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t obd2__obd2_msg_struct__pack_to_buffer(const Obd2__OBD2MsgStruct *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &obd2__obd2_msg_struct__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Obd2__OBD2MsgStruct *obd2__obd2_msg_struct__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Obd2__OBD2MsgStruct *)protobuf_c_message_unpack(&obd2__obd2_msg_struct__descriptor, allocator, len, data);
}
void obd2__obd2_msg_struct__free_unpacked(Obd2__OBD2MsgStruct *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &obd2__obd2_msg_struct__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void obd2__msg_struct__init(Obd2__MsgStruct *message) {
  static const Obd2__MsgStruct init_value = OBD2__MSG_STRUCT__INIT;
  *message = init_value;
}
size_t obd2__msg_struct__get_packed_size(const Obd2__MsgStruct *message) {
  assert(message->base.descriptor == &obd2__msg_struct__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t obd2__msg_struct__pack(const Obd2__MsgStruct *message, uint8_t *out) {
  assert(message->base.descriptor == &obd2__msg_struct__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t obd2__msg_struct__pack_to_buffer(const Obd2__MsgStruct *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &obd2__msg_struct__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Obd2__MsgStruct *obd2__msg_struct__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (Obd2__MsgStruct *)protobuf_c_message_unpack(&obd2__msg_struct__descriptor, allocator, len, data);
}
void obd2__msg_struct__free_unpacked(Obd2__MsgStruct *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &obd2__msg_struct__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor obd2__obd2_data__field_descriptors[23] = {
    {
        "vin", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0,       /* quantifier_offset */
        offsetof(Obd2__OBD2Data, vin), NULL, &protobuf_c_empty_string, 0, /* flags */
        0, NULL, NULL                                                     /* reserved1,reserved2, etc */
    },
    {
        "engine_load", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, engine_load), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                       /* reserved1,reserved2, etc */
    },
    {
        "engine_coolant_temperature", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, engine_coolant_temperature), NULL, NULL, 0,               /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "fuel_pressure", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, fuel_pressure), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                         /* reserved1,reserved2, etc */
    },
    {
        "engine_speed", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, engine_speed), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                        /* reserved1,reserved2, etc */
    },
    {
        "vehicle_speed", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, vehicle_speed), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                         /* reserved1,reserved2, etc */
    },
    {
        "intake_air_temperature", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, intake_air_temperature), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                                  /* reserved1,reserved2, etc */
    },
    {
        "mass_air_flow", 8, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, mass_air_flow), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                         /* reserved1,reserved2, etc */
    },
    {
        "fuel_tank_level_input", 9, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, fuel_tank_level_input), NULL, NULL, 0,               /* flags */
        0, NULL, NULL                                                                 /* reserved1,reserved2, etc */
    },
    {
        "absolute_barometric_pressure", 10, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, absolute_barometric_pressure), NULL, NULL, 0,                /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "control_module_voltage", 11, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, control_module_voltage), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                                   /* reserved1,reserved2, etc */
    },
    {
        "throttle_position", 12, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, throttle_position), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                              /* reserved1,reserved2, etc */
    },
    {
        "ambient_air_temperature", 13, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, ambient_air_temperature), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                                    /* reserved1,reserved2, etc */
    },
    {
        "relative_accelerator_pedal_position", 14, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32,
        0,                                                                            /* quantifier_offset */
        offsetof(Obd2__OBD2Data, relative_accelerator_pedal_position), NULL, NULL, 0, /* flags */
        0, NULL, NULL                                                                 /* reserved1,reserved2, etc */
    },
    {
        "engine_oil_temperature", 15, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, engine_oil_temperature), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                                   /* reserved1,reserved2, etc */
    },
    {
        "engine_fuel_rate", 16, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, engine_fuel_rate), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                             /* reserved1,reserved2, etc */
    },
    {
        "service_distance", 17, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, service_distance), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                             /* reserved1,reserved2, etc */
    },
    {
        "anti_lock_barking_active", 18, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, anti_lock_barking_active), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                                     /* reserved1,reserved2, etc */
    },
    {
        "steering_wheel_angle", 19, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, steering_wheel_angle), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                                 /* reserved1,reserved2, etc */
    },
    {
        "position_of_doors", 20, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, position_of_doors), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                              /* reserved1,reserved2, etc */
    },
    {
        "right_left_turn_signal_light", 21, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, right_left_turn_signal_light), NULL, NULL, 0,                /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "alternate_beam_head_light", 22, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, alternate_beam_head_light), NULL, NULL, 0,                /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "high_beam_head_light", 23, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2Data, high_beam_head_light), NULL, NULL, 0,                /* flags */
        0, NULL, NULL                                                                 /* reserved1,reserved2, etc */
    },
};
static const unsigned obd2__obd2_data__field_indices_by_name[] = {
    9,  /* field[9] = absolute_barometric_pressure */
    21, /* field[21] = alternate_beam_head_light */
    12, /* field[12] = ambient_air_temperature */
    17, /* field[17] = anti_lock_barking_active */
    10, /* field[10] = control_module_voltage */
    2,  /* field[2] = engine_coolant_temperature */
    15, /* field[15] = engine_fuel_rate */
    1,  /* field[1] = engine_load */
    14, /* field[14] = engine_oil_temperature */
    4,  /* field[4] = engine_speed */
    3,  /* field[3] = fuel_pressure */
    8,  /* field[8] = fuel_tank_level_input */
    22, /* field[22] = high_beam_head_light */
    6,  /* field[6] = intake_air_temperature */
    7,  /* field[7] = mass_air_flow */
    19, /* field[19] = position_of_doors */
    13, /* field[13] = relative_accelerator_pedal_position */
    20, /* field[20] = right_left_turn_signal_light */
    16, /* field[16] = service_distance */
    18, /* field[18] = steering_wheel_angle */
    11, /* field[11] = throttle_position */
    5,  /* field[5] = vehicle_speed */
    0,  /* field[0] = vin */
};
static const ProtobufCIntRange obd2__obd2_data__number_ranges[1 + 1] = {{1, 0}, {0, 23}};
const ProtobufCMessageDescriptor obd2__obd2_data__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "obd2.OBD2_data",
    "OBD2Data",
    "Obd2__OBD2Data",
    "obd2",
    sizeof(Obd2__OBD2Data),
    23,
    obd2__obd2_data__field_descriptors,
    obd2__obd2_data__field_indices_by_name,
    1,
    obd2__obd2_data__number_ranges,
    (ProtobufCMessageInit)obd2__obd2_data__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor obd2__obd2_msg_struct__field_descriptors[3] = {
    {
        "timestamp", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
        offsetof(Obd2__OBD2MsgStruct, timestamp), NULL, NULL, 0,          /* flags */
        0, NULL, NULL                                                     /* reserved1,reserved2, etc */
    },
    {
        "deviceID", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_STRING, 0,            /* quantifier_offset */
        offsetof(Obd2__OBD2MsgStruct, deviceid), NULL, &protobuf_c_empty_string, 0, /* flags */
        0, NULL, NULL                                                               /* reserved1,reserved2, etc */
    },
    {
        "obd2_data", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_MESSAGE, 0,               /* quantifier_offset */
        offsetof(Obd2__OBD2MsgStruct, obd2_data), &obd2__obd2_data__descriptor, NULL, 0, /* flags */
        0, NULL, NULL                                                                    /* reserved1,reserved2, etc */
    },
};
static const unsigned obd2__obd2_msg_struct__field_indices_by_name[] = {
    1, /* field[1] = deviceID */
    2, /* field[2] = obd2_data */
    0, /* field[0] = timestamp */
};
static const ProtobufCIntRange obd2__obd2_msg_struct__number_ranges[1 + 1] = {{1, 0}, {0, 3}};
const ProtobufCMessageDescriptor obd2__obd2_msg_struct__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "obd2.OBD2_msg_struct",
    "OBD2MsgStruct",
    "Obd2__OBD2MsgStruct",
    "obd2",
    sizeof(Obd2__OBD2MsgStruct),
    3,
    obd2__obd2_msg_struct__field_descriptors,
    obd2__obd2_msg_struct__field_indices_by_name,
    1,
    obd2__obd2_msg_struct__number_ranges,
    (ProtobufCMessageInit)obd2__obd2_msg_struct__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor obd2__msg_struct__field_descriptors[3] = {
    {
        "hmac", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
        offsetof(Obd2__MsgStruct, hmac), NULL, NULL, 0,             /* flags */
        0, NULL, NULL                                               /* reserved1,reserved2, etc */
    },
    {
        "iv", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
        offsetof(Obd2__MsgStruct, iv), NULL, NULL, 0,             /* flags */
        0, NULL, NULL                                             /* reserved1,reserved2, etc */
    },
    {
        "data", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
        offsetof(Obd2__MsgStruct, data), NULL, NULL, 0,             /* flags */
        0, NULL, NULL                                               /* reserved1,reserved2, etc */
    },
};
static const unsigned obd2__msg_struct__field_indices_by_name[] = {
    2, /* field[2] = data */
    0, /* field[0] = hmac */
    1, /* field[1] = iv */
};
static const ProtobufCIntRange obd2__msg_struct__number_ranges[1 + 1] = {{1, 0}, {0, 3}};
const ProtobufCMessageDescriptor obd2__msg_struct__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "obd2.msg_struct",
    "MsgStruct",
    "Obd2__MsgStruct",
    "obd2",
    sizeof(Obd2__MsgStruct),
    3,
    obd2__msg_struct__field_descriptors,
    obd2__msg_struct__field_indices_by_name,
    1,
    obd2__msg_struct__number_ranges,
    (ProtobufCMessageInit)obd2__msg_struct__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
